### ISSUE TITLE
Add README.md documentation

### ISSUE THREAD

**Issue by danielhan-uc** [TeamFirstCapstone/Pet-Meeting-Client#29]
### Goal of enhancement
Looks like an interesting service that pet owners will love.
I would recommend adding a simple README.md to describe your project as visitors to repo will have easier time understanding and navigating through project.

[Github Guide for README.md](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-readmes)

**Comment by harrywinks** [comment]
I added the README.md for the visitors. 
With the progress of development, README.md will be updated together!
